import Head from 'next/head'

import Banner from '../components/banner'


export default function Home() { 


  return (
    <>
      <Head>
        <title>PORTFÓLIO | JESIEL SILVA</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="banner" href="/favicon.ico" />
      </Head>

      <Banner />
    </>
  )
}
